AWSTemplateFormatVersion: '2010-09-09'
Resources:
  PortfolioVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      Tags: [{Key: Name, Value: Portfolio-VPC}]
  PublicSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref PortfolioVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: us-east-1a
      Tags: [{Key: Name, Value: Portfolio-Public-Subnet}]
