AWSTemplateFormatVersion: '2010-09-09'
Resources:
  AppRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: AppExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement: [{Effect: Allow, Principal: {Service: ec2.amazonaws.com}, Action: sts:AssumeRole}]
      Policies:
        - PolicyName: S3ReadAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement: [{Effect: Allow, Action: ['s3:GetObject', 's3:ListBucket'], Resource: '*'}]
